### ISSUE TITLE
Reporte de inscritos historico

### ISSUE THREAD

**Issue by ymca-mx** [ymca-mx/portal-ingresos#2]
Alejandra y Mayra solicitan que se elabore el reporte para poder visualizar los alumnos inscritos desde el inicio del sistema.

**Comment by ymca-mx** [comment]
Ya se libero y Alejandradio su Vobo.

**Comment by ymca-mx** [comment]
Alejandra dice que le faltan 3 columnas y colores.

**Comment by hbkantonio** [comment]
se libero el reporte.
